import type { Metadata } from "next";
import localFont from "next/font/local"
import { Poppins, } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import "@fortawesome/fontawesome-free/css/all.min.css";

const expandedHeavy = localFont({
  src: "./fonts/sf-ns-expanded-heavy.ttf",
  display: "swap",
  variable: "--font-expanded-heavy",
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.variable} ${expandedHeavy.variable}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
